# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.7
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
- pip install -U tox-travis

script:
- tox

after_success:
- pip install codecov
- codecov

- pip install Sphinx==3.0.3
- pip install sphinx_rtd_theme==0.4.3
- pip install .  # Seems to be required for the apidocs

- cd docs
- sphinx-apidoc ../split_dataset -o ./
- make html
- cd ..

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  - provider: pages
    skip_cleanup: true
    keep_history: true
    github_token:
        secure: "ETZA7jwo3dCxPcX+Xrqi0sWgJu3xFDBb9W4DlbeTPSBGHLezlNiLTUMklvRjlJe5xHZm9GX2yFZheAEIXjQeseqVTAnhCP3JJAwe5G6WMpiCooBnWFMhXvT9T24MlpjIPdmnu7DkmtRqxC6oXk04u65NSn7E8cnpXOf5eKqJbRwcLqj7+q4CWm+CUiiAkgefkM5DrlzWlbVFlJ2ETKjlQgAaGhO/VDaYkEY8EpUjBXtQ29ko2Ns3GY92JSH2iomL+ikdE2BKudNS8ntCXDEoU3YjEpgmYOGY8eO5eG/FljbAcWOTyFKb6trh4oZeik5whjH3ypWMCFCbT12d+0yoHE1vpUpilw9rF1gaXgsbUoa6+wgZT+ZelB8/lpMbz8V4My06uBrippFOOhLT6MM3h1muUMToQAIbyjPocLoc5uJGT6RgctsRmJHO02U3Td+7dsI5/T5vAiwBrvCiAO9qv9k65e4UFmew9pmW8WPCD3ZEya2ScK3kx1LLwjY4mFjjM94FHturQl+pOXtCrjWvtSmQ4Y4zeJqkpMvi58KOWEKNOOCSbhW+pfvVmtyaWuDlmnO7Vl4Vizs1LHe97jBOTNtkbnf80jp7S9j6PtgLFF2FOYkjs8K61k1KTNl2svLiqiEEuuGDMNaM9s2tUFky/j0x97wBd5UOTie6InNwjv0="
    on:
      tags: true
      branch: master
      python: 3.8
    local-dir: docs/_build/html
    committer-from-gh: true

  - provider: pypi
    skip_cleanup: true
    distributions: sdist bdist_wheel
    user: __token__
    password:
        secure: "w9P70D6+4AprlGZ137CBt9Z/oVN6mMaCmexePEJcSrO1a/ZQS71EIpN5/lUjCsGXLeLi7IqIDi6XXwERq879uQnblJal75JY4BsrUiVz9m1pj3BELWUL2TyrGARwzaX8X1Ungz2K1JBWNJvs3shix+Dvz89TeJd47vJYudiOjxP81uirRglnJL8PCbgYpOrzM8VQuv78mK9/y/+O7cj8m4TPbWLS8bJMNXRPsnMNoDQUuzXjPvAfj2SnpAW/19IwBgcSrzFMvs2CJHCZxvtLPo97j2JsqdFDl0P1zw9xbT9NJQfnx7T0FSlTapAO3eTd4W+28LGDWbUgEIbdAWAW0MbbQ7zzeGChmCrOuKNB86aJ/CRWcNQLJ+eTxzNJ0qw/N1w1B3YwBawNWthRBANvFMn4TcE+Gqy64Fiy1wgrHoTDzkqt873KUjQ/mkgwpstk1wYmT1NyOzQTTJOBoEQm6NKcYdfxwpLejYKXvyzsj6S8opj8E39+RuFf4bRHX8paf8vBEI0soXrM8G6afG5Zou/fPE6TH67T1El71VS0UCyq0a+/S7ZfjS6m5UFvBBJrYedNXIpIgR0r+AMDkFBpB6x8lOnn67oVulU/XfGincOuBBDf6saaSYp4Q4AN2Oq/hZXyt4CzGpcWfdqVN0cvM+Ifoaqhml+3EEpElmlCFRE="
    on:
      tags: true
      branch: master
      python: 3.8
    skip_existing: true
