# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Format
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
      with:
        args: .
    
    - uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Apply automatic changes
        branch: ${{ github.head_ref }}
        commit_user_name: Action black fromatter
        commit_user_email: my-github-actions-bot@example.org
        commit_author: Author <actions@github.com>
